[package]
name = "mintpass-core"
version = "0.1.0"
description = "Programa Core para Mintpass — Maneja metadata de eventos y reputación de organizadores"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "mintpass_core"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = { version = "0.32.1", features = ["metadata"] }
