[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "BJcj2Sc2mUTY7TgstZGVwkCuW3JdpeJYoDXccwHiB4uf"
mintpass_escrow = "11111111111111111111111111111111"
mintpass_checkin = "11111111111111111111111111111111"
mintpass_reputation = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
