export interface EventModel {
  id: string | number;
  icon: string;
  color: string;
  bg: string;
  name: string;
  cat: string;
  date: string;
  venue: string;
  duration: string;
  price: number;
  total: number;
  sold: number;
  zones?: Array<{ name: string; price: number; capacity: number; }>;
  limitPerWallet?: number;
  doorTime?: string;
  ageRestriction?: string;
  contactEmail?: string;
  companyName?: string;
  description?: string;
  coverImage?: string;
  ticketImage?: string;
  gallery?: string[];
  city?: string;
  state?: string;
  country?: string;
  coverText?: string;
  coverClass?: string;
  badge?: string;
  bLabel?: string;
  progress?: number;
  progressColor?: string;
  progressLabel?: string;
  statusClass?: string;
  statusText?: string;
  actions?: string[];
  primaryAction?: number;
  meta?: string;
  organizerWallet?: string;
  coverStyle?: any;
  priceStyle?: any;
  status?: string;
  isEventPast?: boolean;
  allowResale?: boolean;
  resaleCapLimit?: number | null;
  allowRefunds?: boolean;
  refundTimeLimit?: number | null;
}
